"""UDF Schema — universal document model definitions."""

from .blocks import (
    Block,
    BlockBase,
    BookmarkBlock,
    ChartBlock,
    CodeBlock,
    CommentBlock,
    DrawingBlock,
    EndnoteBlock,
    EquationBlock,
    FieldBlock,
    FooterBlock,
    FootnoteBlock,
    HeaderBlock,
    HeadingBlock,
    HorizontalRuleBlock,
    ImageBlock,
    ListBlock,
    ListItem,
    OutlineItem,
    PageBreakBlock,
    ParagraphBlock,
    QuoteBlock,
    TableBlock,
    TableCell,
    TableColumnDef,
    TableRow,
    TextArtBlock,
    TextBoxBlock,
    UnknownBlock,
    UnsupportedFeature,
)
from .document import DocumentSchema
from .extensions import (
    DocxExtension,
    FormatExtension,
    HwpExtension,
    HwpxExtension,
    PdfExtension,
    XmlExtension,
    create_extension,
)
from .formats import BlockFormat, CellFormat, PositionInfo, RevisionInfo, TabStop
from .inlines import (
    CodeInline,
    EndnoteRefInline,
    EquationInline,
    FootnoteRefInline,
    ImageInline,
    Inline,
    LinkInline,
    RubyInline,
    TextInline,
)
from .metadata import (
    ColumnDef,
    DocumentMetadata,
    PageBoundary,
    PageMargins,
    SectionDef,
)
from .types import (
    Color,
    Ratio,
    emu_to_pt,
    halfpt_to_pt,
    hwpunit_to_pt,
    mm_to_pt,
    pt_to_emu,
    pt_to_halfpt,
    pt_to_hwpunit,
    pt_to_mm,
    pt_to_px,
    pt_to_twip,
    px_to_pt,
    twip_to_pt,
)

__all__ = [
    # document
    "DocumentSchema",
    # blocks
    "Block",
    "BlockBase",
    "BookmarkBlock",
    "CommentBlock",
    "HeadingBlock",
    "HorizontalRuleBlock",
    "ParagraphBlock",
    "TableBlock",
    "TableCell",
    "TableColumnDef",
    "TableRow",
    "ListBlock",
    "ListItem",
    "ImageBlock",
    "CodeBlock",
    "QuoteBlock",
    "EquationBlock",
    "FootnoteBlock",
    "EndnoteBlock",
    "HeaderBlock",
    "FooterBlock",
    "FieldBlock",
    "TextBoxBlock",
    "DrawingBlock",
    "ChartBlock",
    "TextArtBlock",
    "PageBreakBlock",
    "UnknownBlock",
    "UnsupportedFeature",
    "OutlineItem",
    # inlines
    "Inline",
    "TextInline",
    "LinkInline",
    "ImageInline",
    "FootnoteRefInline",
    "EndnoteRefInline",
    "EquationInline",
    "RubyInline",
    "CodeInline",
    # formats
    "BlockFormat",
    "CellFormat",
    "PositionInfo",
    "TabStop",
    "RevisionInfo",
    # metadata
    "DocumentMetadata",
    "PageMargins",
    "ColumnDef",
    "SectionDef",
    "PageBoundary",
    # types
    "Color",
    "Ratio",
    # unit converters
    "hwpunit_to_pt",
    "pt_to_hwpunit",
    "emu_to_pt",
    "pt_to_emu",
    "halfpt_to_pt",
    "pt_to_halfpt",
    "twip_to_pt",
    "pt_to_twip",
    "mm_to_pt",
    "pt_to_mm",
    "px_to_pt",
    "pt_to_px",
    # extensions
    "FormatExtension",
    "XmlExtension",
    "HwpExtension",
    "HwpxExtension",
    "PdfExtension",
    "DocxExtension",
    "create_extension",
]
